def menu_principal():
    print('=' * 50)
    print('=' * 16, 'BANCO DO BONIN', '=' * 16)
    print('=' * 50)
    print()
    print('1 - Clientes')
    print('2 - Contas')
    print('3 - Operações Bancárias')
    print('4 - Relatórios')
    print('5 - Sair')
    return int(input('Informe a ação desejada: '))
        
def menu_cliente():
    print()
    print('=' * 50)
    print('=' * 15,'CLIENTE', '=' * 15)
    print('=' * 50)
    print()
    print('1 - Cadastrar cliente')
    print('2 - Listar clientes')
    print('3 - Atualizar cliente')
    print('4 - Excluir cliente')
    print('0 - Voltar')
    return int(input('Informe a ação requerida: '))
        

def menu_conta():
    print()
    print('=' * 50)
    print('=' * 15,'CONTA', '=' * 15)
    print('=' * 50)
    print()
    print('1 - Criar conta')
    print('2 - Buscar conta')
    print('3 - Listar contas')
    print('4 - Consultar saldo')
    print('5 - Encerrar conta')
    print('0 - Voltar')
    print('=' * 50)
    return int(input('Digite a Ação requerida: '))

def menu_operacoes():
    print()
    print('=' * 50)
    print('=' * 15,'OPERAÇÕES BANCÁRIAS', '=' * 15)
    print('=' * 50)
    print()
    print('1 - Depositar')
    print('2 - Sacar')
    print('3 - Transferir')
    print('0 - Voltar')
    print('=' * 50)
    return int(input('Informe a ação requerida: '))

def menu_relatorios():
    print()
    print('=' * 50)
    print('=' * 15,'AMBIENTE DE RELATÓRIOS', '=' * 15)
    print('=' * 50)
    print()
    print('1 - Relatório de clientes')
    print('2 - Relatório pde contas')
    print('0 - Voltar')
    return int(input('Informe a ação requerida: '))

def menu_relatorios_clientes():
    print()
    print('=' * 50)
    print('=' * 13,'AMBIENTE DE RELATÓRIOS DOS CLIENTES', '=' * 13)
    print('=' * 50)
    print()
    print('1 - Relatório geral')
    print('2 - Ordem alfabética')
    print('3 - Buscar por CPF')
    print('4 - Faixa etária')
    print('0 - Voltar')
    return int(input('Informe a ação requerida: '))

def menu_relatorios_contas():
    print()
    print('=' * 50)
    print('=' * 13,'AMBIENTE DE RELATÓRIOS DAS CONTAS', '=' * 13)
    print('=' * 50)
    print()
    print('1 - Relatório geral')
    print('2 - Maior saldo')
    print('3 - Nível da conta')
    print('0 - Voltar')
    return int(input('Informe a ação requerida: '))