def menu_principal():
    print('=' * 50)
    print('=' * 16, 'BANCO DO BONIN', '=' * 16)
    print('=' * 50)
    print()
    print('1 - Desejo ser cliente')
    print('2 - Acessar área do servidor')
    print('3 - Acessar área do cliente' )
    print('4 - Relatórios do sistema')
    return int(input('Informe a seleção desejada: '))
        
def menu_servidor():
    print()
    print('=' * 50)
    print('=' * 15,'ÁREA DO SERVIDOR', '=' * 15)
    print('=' * 50)
    print()
    print('1 - Buscar cliente')
    print('2 - Listar clientes')
    print('0 - Voltar')
    return int(input('Informe a ação requerida: '))
        

def menu_cliente():
    print()
    print('=' * 50)
    print('=' * 15,'ÁREA DO CLIENTE', '=' * 15)
    print('=' * 50)
    print()
    print('1 - Consultar Saldo')
    print('2 - Realizar depósito')
    print('3 - Realizar saque')
    print('4 - Realizar transferência')
    print('5 - Fechar conta corrente.')
    print('0 - Voltar')
    print('=' * 50)
    return int(input('Digite a Ação requerida: '))

def menu_relatorios():
    print()
    print('=' * 50)
    print('=' * 15,'AMBIENTE DE RELATÓRIOS', '=' * 15)
    print('=' * 50)
    print()
    print('1 - Relatórios de Clientes')
    print('2 - Relatórios de Contas')
    print('0 - Voltar')
    print('=' * 50)
    return int(input('Informe a ação requerida: '))

def menu_relatorios_clientes():
    print()
    print('=' * 50)
    print('=' * 15,'AMBIENTE DE RELATÓRIOS DOS CLIENTES', '=' * 15)
    print('=' * 50)
    print()
    print('1 - Relatório padrão (Por ID)')
    print('2 - Relatório por nome em ordem alfabética')
    print('3 - Relatório por CPF')
    print('4 - Relatório por faixa etária')
    return int(input('Informe a ação requerida: '))

def menu_relatorios_contas():
    print()
    print('=' * 50)
    print('=' * 13,'AMBIENTE DE RELATÓRIOS DAS CONTAS', '=' * 13)
    print('=' * 50)
    print()
    print('1 - Relatório padrão (Por ID)')
    print('2 - Relatório por maior saldo')
    print('3 - Relatório por nível da conta(Faixa de saldo')
    return int(input('Informe a ação requerida: '))